import js from '@eslint/js';
import globals from 'globals';

// The sensor runs in a browser extension and the tests run under Node, so the
// two file sets get different globals. `dist/` is generated by build.sh.
export default [
  {
    ignores: ['dist/**', 'signed/**'],
  },
  js.configs.recommended,
  {
    files: ['shared/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.webextensions,
      },
    },
  },
  {
    files: ['test/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
  },
];
